### ISSUE TITLE
Add support for PIXI.js v6

### ISSUE THREAD

**Issue by mimshwright** [mimshwright/pixi-tagged-text#52]
Version 6 is out but it's not an automatic upgrade for this library. v6 is written in TypeScript and has much better support for types and drops some legacy support.

Also raises the question of how to version this library to work with each if they're not compatible. 🤔

**Comment by rizen** [comment]
I'm using Pixi.js v6 in my app. As far as I'm concerned you should just target whatever the latest stable is. Especially now as a new library. But in the future, it makes sense too, because existing users (like myself, when v7 comes out) can either stick with the old release of this module if they want v6 support, or upgrade to v7 if they want the latest features.

**Comment by mimshwright** [comment]
Curious how you're managing to use this component with v6? I tried switching it over and it started throwing errors in my project so I decided to hold off for the time being. 

Maybe it's just a typescript thing or something having to do with linking to that dependency.

**Comment by rizen** [comment]
I know nothing of typescript, and am only really getting started with compiled javascript. Is there something I could show you that might help you figure it out? Basically I just ~~~yarn build~~~ and then import it into my app and it works. I haven't tried it since you switched over to the new module name. That's on my todo for this week. I'll let you know how that goes.

**Comment by rizen** [comment]
Ok. I have used PTT v2.0.0 that you have out on NPM in my app which is on Pixi.js v6.0.2 currently. All I had to do to make it work was replace:

```import * as RichText from '@/util/pixi-rich-text/dist/pixi-rich-text.js';```

with 

```import TaggedText from 'pixi-tagged-text';```

And of rename the constructor call from ```RichText()``` to ```TaggedText()```

**Comment by mimshwright** [comment]
That's good news @rizen ! Thanks for the report.

**Comment by mimshwright** [comment]
Since pixi is a (peer) dependency of this library, i will eventually want to upgrade the dependency and fix the compiler errors. So this issue will remain. Since this is not a blocker, I think once I'm sure I have any other planned upgrades and bug fixes i will do this so users of v5 will get the latest version. Hopefully the integrations with v6 will actually be backwards compatible and v5 or v6 can be used.

**Comment by luxaritas** [comment]
Hey all! We use pixi-multistyle-text in https://github.com/eternagame/eternajs, but since that library is no longer maintained, I've been looking for alternatives. I'm planning on just updating our fork for now so that we can upgrade to Pixi 6, but once support is available here, I'd love to migrate.

**Comment by mimshwright** [comment]
@luxaritas according to @rizen it works with v6. It's just got compile issues when you try to build the library itself with v6 as a peer dependency. 

I would appreciate if you wanted to try it out and see if it works for you so we can get some additional data points!

**Comment by luxaritas** [comment]
I'll probably look into this next week - I assume I'd need to use npm's legacy peer deps option in order to install a conflicting version?

I am familiar with TypeScript myself, and was able to get it to build. There were only two issues, one being some bad undefined handling and one being that IFontMetrics is no longer exported from PIXI. Not sure what your preference is to handle the latter, but I just copied the definition into types.ts and used that instead of PIXI.IFontMetrics. I can PR you a change if you want.

**Comment by mimshwright** [comment]
My plan was to switch the peer dep to >6.0.0 and fix any compiler issues with TS. if you've done something like this and want to do a PR, that would be great!

**Comment by mimshwright** [comment]
Trying to see if we can find a way to suppress WebGL errors in tests. 
Created an issue with pixijs team to try to get help. https://github.com/pixijs/pixijs/issues/7554
I'll maybe merge it into a pixi-6 branch for now.

**Comment by mimshwright** [comment]
@luxaritas Looks like I got this all working on the pixi-6 branch using electron to do the testing. I still had the off-by-one pixel errors and I believe that's related to the different testing environments. I fixed that by just testing for either value ¯\_(ツ)_/¯ 
Could you maybe take a look and see if it's all working for you when you have a moment before I merge with main?

**Comment by luxaritas** [comment]
@mimshwright Still seeing some failed tests (this is after checking out `mimshwright/pixi-6`, nuking my `node_modules` and `dist`, and running `yarn && yarn test`):

<details>
<pre>
 FAIL  test/pixiUtils.test.ts
  ● pixiUtils › getFontPropertiesOfText() › should throw an error if the Text has not had updateText() called at least once.

    expect(received).toThrow()

    Received function did not throw

      36 |       expect(() => {
      37 |         pixiUtils.getFontPropertiesOfText(textField);
    > 38 |       }).toThrow();
         |          ^
      39 |     });
      40 |
      41 |     it("should before setting any styles (but after calling updateTexT()) the metrics will be an expected default.", () => {

      at Object.<anonymous> (test/pixiUtils.test.ts:38:10)

  ● pixiUtils › getFontPropertiesOfText() › should before setting any styles (but after calling updateTexT()) the metrics will be an expected default.

    expect(received).toBe(expected) // Object.is equality

    Expected: 6
    Received: 5

      46 |       );
      47 |       expect(defaultFontProps.ascent).toBe(24);
    > 48 |       expect(defaultFontProps.descent).toBe(6);
         |                                        ^
      49 |       expect(defaultFontProps.fontSize).toBe(30);
      50 |     });
      51 |

      at Object.<anonymous> (test/pixiUtils.test.ts:48:40)

  ● pixiUtils › getFontPropertiesOfText() › should provide the correct numbers after changing the style for the text.

    expect(received).toBe(expected) // Object.is equality

    Expected: 7
    Received: 6

      59 |       expect(fontProps.ascent).toBeGreaterThanOrEqual(27);
      60 |       expect(fontProps.ascent).toBeLessThanOrEqual(28);
    > 61 |       expect(fontProps.descent).toBe(7);
         |                                 ^
      62 |       expect(fontProps.fontSize).toBeGreaterThanOrEqual(34);
      63 |       expect(fontProps.fontSize).toBeLessThanOrEqual(35);
      64 |     });

      at Object.<anonymous> (test/pixiUtils.test.ts:61:33)

  ● pixiUtils › getFontPropertiesOfText() › What if the text you want is exactly what the initial value is? › should not throw an error if you happen to set your text to the same value as the initial values.

    expect(received).not.toThrowError()

    Error name:    "Error"
    Error message: "expect(received).toMatchObject(expected)·
    - Expected  - 2
    + Received  + 2·
      Object {
    -   \"ascent\": 9,
    +   \"ascent\": 10,
        \"descent\": 2,
    -   \"fontSize\": 11,
    +   \"fontSize\": 12,
      }"

          79 |             true
          80 |           );
        > 81 |           expect(actualFontProps).toMatchObject(initialFontProps);
             |                                   ^
          82 |         }).not.toThrowError();
          83 |       });
          84 |

      at test/pixiUtils.test.ts:81:35
      at Object.<anonymous> (node_modules/@jest/core/node_modules/expect/build/toThrowMatchers.js:83:11)
      at Object.throwingMatcher [as toThrowError] (node_modules/@jest/core/node_modules/expect/build/index.js:338:21)
      at Object.<anonymous> (test/pixiUtils.test.ts:82:16)
      at Object.<anonymous> (test/pixiUtils.test.ts:82:16)

  ● pixiUtils › getFontPropertiesOfText() › What if the text you want is exactly what the initial value is? › ...however, it will throw if the fontSize is a string (rather than trying to convert it to pxs) unless you use force.

    expect(received).toThrowError()

    Received function did not throw

      90 |         expect(() => {
      91 |           pixiUtils.getFontPropertiesOfText(trickyText, false);
    > 92 |         }).toThrowError();
         |            ^
      93 |
      94 |         expect(() => {
      95 |           pixiUtils.getFontPropertiesOfText(trickyText, true);

      at Object.<anonymous> (test/pixiUtils.test.ts:92:12)

 FAIL  test/layout.test.ts
  ● layout module › calculateFinalTokens() › Stroked text › Shouldn't affect non-strked text. 

    expect(received).toBe(expected) // Object.is equality

    Expected: 5
    Received: 4

      455 |         expect(normal.fontProperties.ascent).toBeGreaterThanOrEqual(18);
      456 |         expect(normal.fontProperties.ascent).toBeLessThanOrEqual(19);
    > 457 |         expect(normal.fontProperties.descent).toBe(5);
          |                                               ^
      458 |         expect(normal.fontProperties.fontSize).toBeGreaterThanOrEqual(23);
      459 |         expect(normal.fontProperties.fontSize).toBeLessThanOrEqual(24);
      460 |         expect(normal.bounds.height).toBe(normal.fontProperties.fontSize);

      at Object.<anonymous> (test/layout.test.ts:457:47)

  ● layout module › calculateFinalTokens() › Stroked text › Should take the stroke into account when determining the size and the fontProperties (for baseline).

    expect(received).toBe(expected) // Object.is equality

    Expected: 25
    Received: 24

      467 |         expect(stroked.fontProperties.ascent).toBeGreaterThanOrEqual(38);
      468 |         expect(stroked.fontProperties.ascent).toBeLessThanOrEqual(39);
    > 469 |         expect(stroked.fontProperties.descent).toBe(25);
          |                                                ^
      470 |         expect(stroked.fontProperties.fontSize).toBeGreaterThanOrEqual(63);
      471 |         expect(stroked.fontProperties.fontSize).toBeLessThanOrEqual(64);
      472 |         expect(stroked.bounds.height).toBe(stroked.fontProperties.fontSize);

      at Object.<anonymous> (test/layout.test.ts:469:48)

  ● layout module › calculateFinalTokens() › Stroked text › Should not affect any other stroked text. Sometimes this happens when fontProperties are shared. 

    expect(received).toBe(expected) // Object.is equality

    Expected: 25
    Received: 24

      479 |         expect(alsoStroked.fontProperties.ascent).toBeGreaterThanOrEqual(38);
      480 |         expect(alsoStroked.fontProperties.ascent).toBeLessThanOrEqual(39);
    > 481 |         expect(alsoStroked.fontProperties.descent).toBe(25);
          |                                                    ^
      482 |         expect(alsoStroked.fontProperties.fontSize).toBeGreaterThanOrEqual(63);
      483 |         expect(alsoStroked.fontProperties.fontSize).toBeLessThanOrEqual(64);
      484 |         expect(alsoStroked.bounds.height).toBe(

      at Object.<anonymous> (test/layout.test.ts:481:52)

 FAIL  test/TaggedText.test.ts
  ● Console

    console.log
      
      =====

      at TaggedText.Object.<anonymous>.TaggedText.update (src/TaggedText.ts:453:15)

    console.log
      This should appear in console!
      =====
      
      "This": (0/0/0)
          tags: <none>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial
          size: x:0 y:0 width:19 height:11 bottom:11 right:19
          font: fontSize:11 ascent:9 descent:2,
      " ": (0/1/0)
          tags: <none>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial
          size: x:19 y:0 width:3 height:11 bottom:11 right:22
          font: fontSize:11 ascent:9 descent:2,
      "should": (0/2/0)
          tags: <b>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial; fontWeight:bold
          size: x:22 y:0 width:33 height:11 bottom:11 right:55
          font: fontSize:11 ascent:9 descent:2,
      " ": (0/3/0)
          tags: <b>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial; fontWeight:bold
          size: x:55 y:0 width:3 height:11 bottom:11 right:58
          font: fontSize:11 ascent:9 descent:2,
      "appear": (0/4/0)
          tags: <b>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial; fontWeight:bold
          size: x:58 y:0 width:33 height:11 bottom:11 right:91
          font: fontSize:11 ascent:9 descent:2,
      " ": (0/5/0)
          tags: <none>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial
          size: x:91 y:0 width:3 height:11 bottom:11 right:94
          font: fontSize:11 ascent:9 descent:2,
      "in": (0/6/0)
          tags: <none>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial
          size: x:94 y:0 width:8 height:11 bottom:11 right:102
          font: fontSize:11 ascent:9 descent:2,
      " ": (0/7/0)
          tags: <none>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial
          size: x:102 y:0 width:3 height:11 bottom:11 right:105
          font: fontSize:11 ascent:9 descent:2,
      "console!": (0/8/0)
          tags: <none>
          style: align:left; valign:baseline; imgDisplay:inline; wordWrap:true; wordWrapWidth:500; lineSpacing:0; fill:0; fontSize:10; fontFamily:arial
          size: x:105 y:0 width:38 height:11 bottom:11 right:143
          font: fontSize:11 ascent:9 descent:2

      at TaggedText.Object.<anonymous>.TaggedText.update (src/TaggedText.ts:453:15)

    console.log
      { timeControl: 376, timeSkipDraw: 203, timeSkipUpdates: 10 }

      at Suite.<anonymous> (test/TaggedText.test.ts:422:17)

  ● TaggedText › text › multiple lines › Should support text with multiple lines.

    expect(received).toBe(expected) // Object.is equality

    Expected: 1
    Received: 0.9166666666666666

      524 |         const H3 = tripleSpacedLines.getBounds().height / fontSize;
      525 |
    > 526 |         expect(H).toBe(1);
          |                   ^
      527 |         expect(H2).toBeCloseTo(2, 0);
      528 |         expect(H3).toBeCloseTo(4, 0);
      529 |       });

      at Object.<anonymous> (test/TaggedText.test.ts:526:19)
</pre>
</details>

**Comment by mimshwright** [comment]
> Still seeing some failed tests (this is after checking out `mimshwright/pixi-6`, nuking my `node_modules` and `dist`, and running `yarn && yarn test`):

Damn. Can you give me your OS and versions of node, npm and yarn?

Thanks

**Comment by mimshwright** [comment]
Also @luxaritas I just pushed another version to that branch merging with main.

**Comment by mimshwright** [comment]
For the record, I'm on 
MacOS v11.4
node v16.2.0
npm v7.13.0
yarn v1.22.10

**Comment by luxaritas** [comment]
Manjaro v21.0.7
node v14.16.0
npm v7.16.0
yarn v1.22.10

**Comment by mimshwright** [comment]
I tried it using node v14.16.0 and npm v7.17.0 but got the same results. 
So if it's one of those things, it's probably related to the OS which unfortunately I won't really be able to test myself. I mean that seems likely since it's now running the tests in an instance of Electron which might operate slightly differently on Linux. 

Still I am curious if others users (on windows or Mac) are getting different results from running tests. If so, I probably need to change the testing environment again.

**Comment by luxaritas** [comment]
AFAIK these failures were the same for me before the environment change. I did a rough bisect a while ago and the failures seemed to pop up piecemeal over time - I'd need to go back and run through it again to isolate the commits.

**Comment by mimshwright** [comment]
I just fired up Parallels and tested under windows 10. Looks like I got some of the same or similar errors to you...

 FAIL  test/layout.test.ts
  layout module
    updateOffsetForNewLine()
      √ should update the properties of the offset. x would always be zero in this case.
      √ should return a copy of the input, not the original input.
    concatBounds()
      √ Should combine two bounds into one.
    getBoundsNested()
      √ Should return the bounding box of a nested group of tokens.
    translatePoint()
      √ should move a point-like object by an amount.
      √ should create a new object rather than editing the original.
    translateLine()
      √ should offset several points (all the Measurements in a line)
      √ should create a new object rather than editing the original.
    lineWidth()
      √ should get the total width of the words in a line of measurements.
      √ should assume that the lines are sorted already left to right.
      √ should account for positioning of first and last elements.
    alignLeft()
      √ should align a single line of text to the left.
      √ should not matter if the original items are out of place nor if the y value isn't the same for all items.
    alignRight()
      √ should align a single line of text to the right.
    alignCenter()
      √ should align a single line of text to the right.
    alignJustify()
      √ should position the words in a line so that they fill the maximum possible space available. It should assume that the array is sorted left to right and that the words all fit inside the space.
      √ Should ignore elements that have width of zero.
      √ should create a new object rather than editing the original.
      √ should return an empty object if given an empty object.
      √ should return the first object positioned left if there is only one element.
    splitAroundWhitespace()
      √ Should split at every whitespace but not delete the whitespace, keept it. (63 ms)
    splitText()
      √ Should split words into segments. If you choose words, it will split on whitespace.
      √ Should split on character if specified
      √ Should treat every whitespace as a separate piece.
      √ Should throw if the method is unknown. (15 ms)
    calculateFinalTokens()
      √ Should throw if the styledToken has no style
      wordWrap and wordWrapWidth properties
        Should respect the wordWrap property
          √ When wordWrap is true, use the wordWrapWidth to determine the maximum width of a line. (47 ms)
          √ When wordWrap is true, text can sometimes be larger than wordWrapWidth if a single word is very long. (47 ms)
          √ When wordWrap is true but wordWrapWidth is undefined, 0, negative, or NaN, it is unbounded. (141 ms)
          √ When wordWrap is false, text can continue to grow horizontally indefinitely (31 ms)
      Stroked text
        **× Shouldn't affect non-strked text.  (16 ms)
        × Should take the stroke into account when determining the size and the fontProperties (for baseline).
        × Should not affect any other stroked text. Sometimes this happens when fontProperties are shared.**
      Text with textTransform style
        √ Should calculate sizes of text that has textTransform style correctly without actually changing the content for them.
      Scaled text
        √ Default should be 1x scale for X and Y.
        √ Should scale the width of text.
        √ Scale the height of text by using fontSize and <100% font scaling. (15 ms)
        √ Should convert NaN to 0
        √ Should convert negative numbers to 0
      splitStyle
        √ Should split on whitespace by default
        √ Should split on character if specified (16 ms)
      collapseWhitespacesOnEndOfLines()
        √ Should collapse the width of any whitespace characters that appear at end of lines. (but not in middle)
        √ Should collapse width and height of newlines.
      end to end conversion
        √ Should have default styles for styleTokens
        √ Most words should have length 0 but Should treat SuPeR! as one word
        √ Should give similar size properties to text with the same styles and same text.
        √ Should fully convert text to final tokens.
        √ Should unset styles when there are no styles
    verticalAlignInLines()
      √ should position text vertically in a line so that it fits correctly.
      √ should create a new object rather than editing the original.

 FAIL  test/pixiUtils.test.ts
  pixiUtils
    cloneSprite()
      √ should create a shallow copy of a sprite.
    checkPixiVersion()
      √ should throw if the version doesn't exactly match (15 ms)
      √ should return 0 otherwise
    getFontPropertiesOfText()
      **× should throw an error if the Text has not had updateText() called at least once.
      × should before setting any styles (but after calling updateTexT()) the metrics will be an expected default. (16 ms)
      × should provide the correct numbers after changing the style for the text.
      What if the text you want is exactly what the initial value is?
        × should not throw an error if you happen to set your text to the same value as the initial values. (31 ms)
        × ...however, it will throw if the fontSize is a string (rather than trying to convert it to pxs) unless you use force.**

**Comment by mimshwright** [comment]
This is basically on hold til i have time to write the tests so that they are broad enough to run and pass on both Windows and Mac.

**Comment by mimshwright** [comment]
I'm working on v6 support again. 

I noticed that in v6.2+ the tests break and require `jest-electron` to run.  For reference, here is an issue I logged: https://github.com/pixijs/pixijs/issues/8197
